version: "3.8"

services: 
  vuejs:
    image: node:lts
    container_name: vuejs
    volumes: 
      - ./app:/home/node/app
    ports: 
      - 8080:8080
      - 8081:8081
      - 8082:8082
      - 8083:8083
      - 8084:8084
    working_dir: /home/node/app
    user: node
    tty: true
    restart: always
